import { Router } from "express";
import auth from "../middleware/auth.js";
import { requireHR, requireEmployee } from "../middleware/roles.js";
import { getNotifications, getMyNotifications, createNotification, markNotificationRead, markAllNotificationsRead, deleteNotification } from "../controllers/notificationsController.js";
const router=Router();
router.get("/",auth,requireHR,getNotifications);
router.get("/mine",auth,requireEmployee,getMyNotifications);
router.post("/",auth,requireEmployee,createNotification);
router.patch("/:id/read",auth,requireHR,markNotificationRead);
router.patch("/read-all",auth,requireHR,markAllNotificationsRead);
router.delete("/:id",auth,requireHR,deleteNotification);
export default router;